export const fields = {
  name: ["Name", "Full Name", "Name:", "الإسم:"],
  docNumber: ["Doc Number", "Document Number", "Doc No", "Doc No:"],
  id: [
    "ID",
    "ID:",
    "ID Number",
    "Identity Number",
    "ID No:",
    "الرقم الوطني:",
    "رقم الهوية",
    "رقم الهوية:",
    "الرقم الوطني :",
  ],
  birthDate: [
    "Birth Date",
    "DOB",
    "Date of Birth",
    "D.O.B:",
    "تاريخ الولادة:",
    "تاريخ الولادة :",
  ],
  sex: ["Sex", "Gender", "الجنس :", "الجنس:"],
  expires: ["Expires", "Expires:"],
  nationality: ["Nationality", "Nationality:", "الجنسية", "الجنسية:"],
  surname: ["surname", "surname:"],
  middlename: ["middlename", "middlename:"],
  givenname: ["givenname", "givenname:"],
  mother_name: ["Mother Name", "اسم الام"],
  issued: ["issued", "issued:", "issued :"],
};
